---
title: "Workshop: Finding and using Jornada data"
description: "The Jornada IM team will provide a tour of key Jornada datasets, and demonstrate how to access and use them, at the 2026 Jornada Desert Ecology Short Course"
author: "Greg Maurer"
date: "2026-08-05"
date-modified: "2026-08-03"
draft: False
---

At this workshop, the Jornada IM team will provide a tour of key Jornada datasets and demonstrate how to access and use them with a variety of methods.

## Workshop details

**Date and time:** Wednesday, August 5th, 1:30 pm  
**Location:**  Wooton Hall Auditorium on NMSU campus ([directions](https://lter.jornada.nmsu.edu/contact-info/))  
**What to bring:** Bring a charged laptop and be ready to ask questions about the Jornada data that is most useful to you. 

We recommend working through some data exercises with the analysis platform of your choice (R, Excel, etc.). We will also be downloading data from the web, so make a workshop folder that can be a destination for these datasets.

## Materials

The [slide deck](https://docs.google.com/presentation/d/16ZjZCHqXlNT4e3kxrOE6nXBvfgkedaB_/edit?usp=sharing&ouid=111773368354235849590&rtpof=true&sd=true) we will be working from.

We will also make notes and report back from activities in [this communal notes document](https://docs.google.com/document/d/1edMJalvkjvWuZ-K5Gy4rRPoVxtdGz0ZjWG-LOfrwy2s/edit?usp=sharing)

Greg and Darren have prepared 2 R scripts. If you are using R you may download them from [this folder](https://drive.google.com/drive/folders/1Fklqgt6EqV-RQ-YrBTj8ESKr2UeCIuiZ?usp=sharing).

## Agenda

| Time | Agenda Item | Link to materials |
|---|---|---|
| 1:30 pm | 1. Tour of Jornada datasets | [Slide deck](https://docs.google.com/presentation/d/16ZjZCHqXlNT4e3kxrOE6nXBvfgkedaB_/edit?usp=sharing&ouid=111773368354235849590&rtpof=true&sd=true) |
| | &nbsp;&nbsp;1.1 Intro | |
| | &nbsp;&nbsp;1.2 Long-term vegetation | |
| | &nbsp;&nbsp;1.3 Weather and climate | |
| | &nbsp;&nbsp;1.4 Spatial data (GIS) | |
| | &nbsp;&nbsp;1.5 Remote sensing & aerial imagery | |
| 2:30 pm | 2. Finding Jornada data | [Slide deck](https://docs.google.com/presentation/d/16ZjZCHqXlNT4e3kxrOE6nXBvfgkedaB_/edit?usp=sharing&ouid=111773368354235849590&rtpof=true&sd=true) and live demo at sites below |
| | &nbsp;&nbsp;2.1 JRN data catalog | [lter.jornada.nmsu.edu](https://lter.jornada.nmsu.edu) |
| | &nbsp;&nbsp;2.2 Data viewer | [JRN data viewer app](https://lter.jornada.nmsu.edu/interactive-data-viewer/) |
| | &nbsp;&nbsp;2.3 EDI repository portal | [portal.edirepository.org](https://portal.edirepository.org) |
| | &nbsp;&nbsp;2.4 Jornada GeoPortal | [jornada-geoportal-nmsu.hub.arcgis.com](https://jornada-geoportal-nmsu.hub.arcgis.com/) |
| | &nbsp;&nbsp;2.5 Other | |
| 3:15 pm | **Break** | |
| 3:30 pm | 3. Access/use JRN data (hands-on) | |
| | &nbsp;&nbsp;3.1 Web access (website, EDI, GeoPortal) | live demo | 
| | &nbsp;&nbsp;3.2 EDIutils | [ANPP R script](https://drive.google.com/file/d/1m67RuHlHYueMmfSn_7rdSB1E58C2TOXp/view?usp=sharing) |
| | &nbsp;&nbsp;3.3 RAP | [RAP R script](https://drive.google.com/file/d/1q8nXgUibpMk6-Hd3sflRHybkPZnxx-tu/view?usp=drive_link) |
| | &nbsp;&nbsp;3.4 Other? | |
| 5:00 pm | Fin... | |

