---
title: Forms and templates
---

Below are some forms and templates you will probably need at some point during your Jornada research.

**Research approval**

To request approval to conduct research at the Jornada, fill out the [ResNotif form](Jornada_resnotif_form.docx) and send to the Jornada Research Site Manager (Conrad Nelson, {{< var email.jrn_rsm >}}).

**Project management information**

To update the Jornada team about changes to your project use the [ProjectInfo form](Jornada_projectinfo_template.docx). You can send this to the Jornada IM team ({{< var email.jrn_im >}})

**Metadata templates and dataset preparation**

If you are collecting metadata for your research, you are welcome to use one of these handy **Jornada metadata templates** to help you collect, organize and store complete metadata:

* [MS Word format](Jornada_metadata_template.docx) for relatively simple datasets with few tables.
* [MS Excel format](Jornada_metadata_template.xlsx) for more complex datasets with multiple tables.

When you are ready to prepare a Jornada dataset for publication, we strongly recommend using the Environmental Data Initiative's [ezEML]({{< var url.ezeml >}}) application. You can follow our instructions [here](../docs/researcher/prepare-and-publish.qmd), and it should be easy to transfer information from the templates above. When you are ready to publish you will need to send your metadata and data to the Jornada IM team ({{< var email.jrn_im >}}). You can do this easily through ezEML, or send the templates and data files via email.

**Data requests**

Most data are openly available at the Jornada LTER [website data catalog](https://lter.jornada.nmsu.edu/data-catalog), but some spatial data are restricted access only. To request spatial data, fill out the [Jornada Spatial Data Policy Agreement](https://docs.google.com/forms/d/e/1FAIpQLSdJijSKE4C9G5pgB__yGelBx5j9OPBSKOoCg4MJP-eb-Isiew/viewform?usp=dialog). You can also request to join the [Jornada GeoPortal](https://jornada-geoportal.nmsu.maps.arcgis.com) with this form.