theme: jekyll-theme-minimal
title: [Information Management and Data Science at]
description: [Information for researchers and data managers at the Jornada Basin LTER and Jornada Experimental Range]
logo: [images/JER_logo-wht.png]
