theme: jekyll-theme-minimal
title: "Information Management and Data Science at"
description: "Resources for researchers and data managers at the Jornada Basin LTER and Jornada Experimental Range. Contact: datamanager.jrn.lter@gmail.com"
logo: ./images/logo-LTER.png

highlighter: rouge
