theme: jekyll-theme-minimal
title: "Information Management and Data Science at"
description: "Resources for researchers and data managers at the Jornada Basin LTER"
logo: ./images/JER_logo-wht.png

highlighter: rouge
