theme: jekyll-theme-minimal
title: "Information Management and Data Science at the Jornada"
description: "Resources for researchers and data managers at the Jornada Basin LTER and USDA-ARS Jornada Experimental Range. Contact: jornada.data@nmsu.edu"
logo:
show_downloads: false
highlighter: rouge
