theme: jekyll-theme-minimal
title: [Jornada Information Management and Data Science]
description: [Information for researchers and data managers at the Jornada Basin LTER and Jornada Experimental Range]
logo: [images/JER_logo-wht.png]
