project:
  type: website
  output-dir: _site

website:
  title: "Jornada Data Commons"
  description: "Community resources for researchers and data managers at the Jornada Basin LTER and USDA-ARS Jornada Experimental Range. Contact: jornada.data@nmsu.edu."
  favicon: img/jrn-logo-light.png
  site-url: https://jornada-im.github.io
  repo-url: https://github.com/jornada-im/jornada-im.github.io
  issue-url: https://github.com/jornada-im/jornada-im.github.io/issues/new/choose
  repo-branch: main
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: true
  #announcement: 
  #  content: "**Prerelease version**: This content is under development. See [here](https://ediorg.github.io/data-package-best-practices/) for community-accepted documents." 
   # position: above-navbar
   # dismissable: false
   # type: danger
  search:
    location: navbar
  navbar:
    logo: img/jrn-logo-light.png
    #background: light
    left:
      - text: "Home"
        href: index.qmd
      - text: "Researcher Guide"
        href: docs/researcher/overview.qmd
      - text: "IM Guide"
        href: docs/im/overview.qmd
    tools:
      - icon: github
        href: https://github.com/jornada-im/jornada-im.github.io
        text: Jornada IM GitHub repository

  sidebar:
    - title: "Researcher Guide"
      #id: researcher_docs
      style: floating
      collapse-level: 2
      contents:
        - href: docs/researcher/overview.qmd
          text: Overview
        - href: docs/refs_and_links.md
          text: "Useful references and links"
    - title: "IM Guide"
      #id: im_docs
      style: floating
      collapse-level: 2
      contents:
        - href: docs/im/overview.qmd
          text: Overview
        - section: "Full IM System Documentation"
          href: docs/im/sysadmin/index.qmd
          contents:
            - href: docs/im/sysadmin/chapter-01-overview.qmd
              text: "Overview"
        - href: docs/refs_and_links.md
          text: "Useful references and links"

execute:
  freeze: auto

#bibliography: references.bib

format:
  html:
    theme: sandstone
    highlight-style: pygments
    #code-block-bg: true
    #code-block-border-left: "#31BAE9"
    fontsize: 1.0em
    toc: true

