project:
  type: website
  output-dir: _site

website:
  title: "Jornada Data Commons"
  description: "Community resources for researchers and data managers at the Jornada Basin LTER and USDA-ARS Jornada Experimental Range. Contact: jornada.data@nmsu.edu."
  favicon: img/jrn-logo-light.png
  site-url: https://jornada-im.github.io
  repo-url: https://github.com/jornada-im/jornada-im.github.io
  issue-url: https://github.com/jornada-im/jornada-im.github.io/issues/new/choose
  repo-branch: main
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: true
  #announcement: 
  #  content: "**Prerelease version**: This content is under development. See [here](https://ediorg.github.io/data-package-best-practices/) for community-accepted documents." 
   # position: above-navbar
   # dismissable: false
   # type: danger
  search:
    location: navbar
  navbar:
    logo: img/jrn-logo-light.png
    #background: light
    left:
      - text: "Researcher Guide"
        href: docs/researcher/overview.qmd
      - text: "IM Guide"
        href: docs/im/overview.qmd
      - text: "Document Archive"
        menu:
          - templates/index.qmd
          - proposals-and-reports/index.qmd
          - archive/index.qmd
      - text: "Updates"
        href: posts/posts.qmd
    tools:
      - icon: github
        href: https://github.com/jornada-im/jornada-im.github.io
        text: Jornada IM GitHub repository

  sidebar:
    - title: "Researcher Guide"
      #id: researcher_docs
      style: floating
      collapse-level: 2
      contents:
        - href: docs/researcher/overview.qmd
          text: Overview
        - href: docs/refs_and_links.qmd
          text: "Useful references and links"
    - title: "IM Guide"
      #id: im_docs
      style: floating
      collapse-level: 2
      contents:
        - href: docs/im/overview.qmd
          text: "Overview"
        - section: "Metadata standards"
          contents: docs/im/standards/*
        - section: "Procedures"
          contents: docs/im/procedures/*
        - section: "Hacks"
          contents: docs/im/hacks/*
        - section: "Full IM System Documentation"
          href: docs/im/sysadmin/index.qmd
          contents: docs/im/sysadmin/*
            # - href: docs/im/sysadmin/chapter-01-overview.qmd
            #   text: "Overview"
            # - href: docs/im/sysadmin/chapter-02-website-and-comm.qmd
            #   text: "Website and communications"
            # - href: docs/im/sysadmin/chapter-03-jrn-metabase.qmd
            #   text: "Metabase"
            # - href: docs/im/sysadmin/chapter-04-publishing-data.qmd
            #   text: "Data publishing"
            # - href: docs/im/sysadmin/chapter-05-server-admin.qmd
            #   text: "Server administration"
        - href: docs/refs_and_links.qmd
          text: "Useful references and links"

execute:
  freeze: auto

#bibliography: references.bib

format:
  html:
    theme: sandstone
    highlight-style: pygments
    #code-block-bg: true
    #code-block-border-left: "#31BAE9"
    fontsize: 1.0em
    toc: true

