---
title: Discover research data at Jornada and beyond
date: last-modified
from: markdown+emoji
slide-format: revealjs
---

## Overview

:construction: **Most of this chapter is under construction.**

Multiple research programs, with different personnel and scientific priorities, overlap in the Jornada Basin. Both the JRN LTER program and the USDA-ARS Jornada Experimental Range have collected and published environmental datasets over many decades, and numerous more recent research and monitoring programs operate in the region, leveraging the research infrastructure and baseline data at the Jornada. This results in a large diversity of data sources and types, each having different management needs and histories. Tracking Jornada datasets and making them discoverable and usable is a major challenge, and the motivating purpose for the Jornada Information Management team.

## How data are organized

 Currently there are three overlapping systems we use to organize the data for discovery, management and reporting. First, there are several **collection types**, which are broad categories of datasets defined by the source of the data and where they are published or made available. Second, almost all Jornada research, so long as it includes a field component, receives a **study ID** number that uniquely identifies the research project and connects to associated information (investigators, location, research purpose, datasets). Finally, most Jornada studies and data fall into particular **research themes**, and datasets are keyworded appropriately for these themes.

### Collection type

* **Core datasets** are collected with direct support from the JRN LTER program long-term program
* **Contributed datasets** are collected by investigators, students, or others affiliated with JRN LTER or JER programs and then contributed to the Jornada data catalog.
* **Partner data** come from external partners who collect data at or about the Jornada. NOAA, NEON, and NRCS are examples.
* **Spatial data** are collected by Jornada staff or partners and are managed within the Jornada GeoPortal.

### Study ID

* There are over 600 named studies in the Jornada Basin. These are given sequential, three-digit identifier codes (001, 002,...621) that also become part of the dataset identifier when published.

### Research theme

There are a number of prominent research themes that Jornada investigations center on, and datasets can be organized around these themes using thematic keywords in the metadata. Currently those themes include:

* Vegetation dynamics
* Climate & environmental monitoring
* Management & restoration
* Biogeochemistry
* Hydrology
* Aeolian processes
* Trophic interactions
* Physical geography & soils

## The Jornada data catalogs

Given the diversity of Jornada research and data products, things are published in multiple repositories and must be cataloged different ways. The primary access point for all data (and other research products, like book and journal publications) is through the [Jornada LTER website](https://lter.jornada.nmsu.edu). On the Jornada website there are two primary data access points:

1. The [JRN LTER primary data catalog](https://lter.jornada.nmsu.edu/data-catalog/) currently provides access to Jornada data held in multiple repositories with a faceted interface. The five tabs in the data catalog are:

    * [Tab 1](https://lter.jornada.nmsu.edu/data-catalog/#uagb-tabs__tab0): A list of links featuring the most important core, long-term datasets collected at JRN, arranged by important research themes.
    * [Tab 2](https://lter.jornada.nmsu.edu/data-catalog/#uagb-tabs__tab1): A searchable listing of all datasets held in our primary data catalog, hosted at the EDI repository.
    * [Tab3](https://lter.jornada.nmsu.edu/data-catalog/#uagb-tabs__tab2): Is a searchable listing of Jornada data held in other repositories (not EDI).
    * [Tab 4](https://lter.jornada.nmsu.edu/data-catalog/#uagb-tabs__tab3): A listing of a few of the most useful spatial datasets the Jornada has. This catalog will be updated soon.
    * [Tab 5](https://lter.jornada.nmsu.edu/data-catalog/#uagb-tabs__tab4): A listing of Jornada "data partnerships", with relevant links to data catalogs provided and managed by collaborating research networks working in the Jornada Basin are.

2. The [interactive data viewer](https://lter.jornada.nmsu.edu/interactive-data-viewer/) allows map-based browsing of some of our long-term meteorology and ecology datasets collected at the Jornada.

## Search out Jornada data in other places

* EDI
* DataONE
* Google Dataset Search

## Jornada GeoPortal

* Spatial data in the NMSU ArcGIS Online platform

## Partner data

* Partner data listings

## Ancillary data

* Not collected by Jornada programs or partners, but still useful.
