---
title: Research policies and permitting
author: The Jornada Information Management Team
date: last-modified
---

## Obtaining permits 

Most new research projects are initiated through the Jornada Research Site Manager, John Anderson (<janderso@nmsu.edu>). The [JRN website](https://lter.jornada.nmsu.edu/for-researchers) or the [JER website](https://jornada.nmsu.edu/researcher-information) are the best source of information on this process, and have the current forms needed. To begin the approval process, a potential researcher submits a Research Notification (ResNotif) form, which describes the planned location, research activities, personnel, and other important project information, to John Anderson. After review, and after any necessary changes to the plan are made, the project may be approved to begin.

All approved research projects at the Jornada must agree to a data sharing and acknowledgement policy. The requirements for Jornada researchers are, again, detailed on the [JRN](https://lter.jornada.nmsu.edu/for-researchers) or [JER](https://jornada.nmsu.edu/researcher-information) websites, but to summarize, researchers should:

1. Submit research data and metadata for publication
    - We require most researchers to submit data and metadata yearly to our research data archive. We publish this data in open-access repositories at the time research results are peer-reviewed and published, or no later than 2 years after collection. This keeps the program in step with the [LTER data policy](https://lternet.edu/data-access-policy/) and other relevant guidelines.
2. Keep research project information up to date
    - We ask that approved projects submit any major post-approval changes to the project as a revised ResNotif form, or at a minimum regularly provide updates on the project, its personnel, and progress.
3. Acknowledge Jornada LTER and USDA-ARS support
    - The support received, name of the program, and relevant grant numbers should be included in the acknowledgement section of any journal article, dissertation, or other publication. Support is defined as direct funding of research or personnel costs allocated from the Jornada grants, fellowship support to graduate students, logistical or data collection support from the Jornada field crew, or data management services from the Jornada Information Management team.
4. Cite the Jornada LTER and USDA-ARS data used in your research
    - When research findings involving Jornada data appear in a publication (journal article, dissertation, website, etc.), please include a citation and link to the original data. For already-published long-term datasets include a DOI link at a minimum, and if possible, a full citation in the reference section (e.g. in a journal article). If the data are new and unpublished, please publish the dataset AND cite it in the publication.

The Jornada IM team strives to uphold high data publishing standards, so Jornada students and investigators who contribute to research at the Jornada should be aware of, or be willing to learn about, some best practices for collecting and describing their research data.
