---
title: Starting a Jornada research project
date: last-modified
---

## Overview

To start your research you will need a plan. Overall, your research plan may be full of things like experimental design, field logistics, and other tough decisions. Most of these are beyond the scope of this guide, which focuses on the data you'll be collecting, analyzing and publishing, but you do need to have your plan approved by the Jornada Research Site Managers, and we strongly recommend planning in advance for data management. In this chapter we help you plan for and navigate the Jornada permitting and project management process, and give some advice on creating your own data management plan (DMP).


## Permit approval process

Most new research projects are initiated through the Jornada Research Site Manager, Conrad Nelson (<cwnelson@nmsu.edu>). The [JRN website](https://lter.jornada.nmsu.edu/for-researchers) or the [JER website](https://jornada.nmsu.edu/researcher-information) are the best source of information on this process, and have the current forms needed. There is also a listing of forms available [here](../../templates/index.qmd). To begin the approval process, a potential researcher submits a Research Notification (ResNotif) form, which describes the planned location, research activities, personnel, and other important project information, to Conrad Nelson. After review, and after any necessary changes to the plan are made, the project can be approved to begin.

### The Jornada data policy

All approved research projects at the Jornada must agree to a data sharing and acknowledgement policy. The requirements for Jornada researchers are, again, detailed on the [JRN](https://lter.jornada.nmsu.edu/for-researchers) or [JER](https://jornada.nmsu.edu/researcher-information) websites, but to summarize, researchers should:

::: {.callout-note collapse="true" icon="false" appearance="minimal"}
## 1. Submit research data and metadata for publication.
We require most researchers to submit data and metadata yearly to our research data archive. We publish this data in open-access repositories at the time research results are peer-reviewed and published, or no later than 2 years after collection. This keeps the program in step with the [LTER data policy](https://lternet.edu/data-access-policy/) and other relevant guidelines.
:::
::: {.callout-note collapse="true" icon="false" appearance="minimal"}
## 2. Keep research project information up to date.
We ask that approved projects submit any major post-approval changes to the project as a revised ResNotif form, or at a minimum regularly provide updates on the project, its personnel, and progress. Check the instructions [below](#updating-your-plan-and-project-information) to do that.
:::
::: {.callout-note collapse="true" icon="false" appearance="simple"}
## 3. Acknowledge Jornada LTER and USDA-ARS support.
The support received, name of the program, and relevant grant numbers should be included in the acknowledgement section of any journal article, dissertation, or other publication. Support is defined as direct funding of research or personnel costs allocated from the Jornada grants, fellowship support to graduate students, logistical or data collection support from the Jornada field crew, or data management services from the Jornada Information Management team.
:::
::: {.callout-note collapse="true" icon="false" appearance="minimal"}
## 4. Cite the Jornada LTER and USDA-ARS data used in your research.
When research findings involving Jornada data appear in a publication (journal article, dissertation, website, etc.), please include a citation and link to the original data. For already-published long-term datasets include a DOI link at a minimum, and if possible, a full citation in the reference section (e.g. in a journal article). If the data are new and unpublished, please publish the dataset AND cite it in the publication.
:::

The Jornada IM team strives to uphold high data publishing standards, so Jornada students and investigators who contribute to research at the Jornada should be willing to learn about, and adhere to, some best practices for collecting, describing, and publishing their research data.

## Making a data management plan

Managing the data you collect and use is an integral part of any research project, and you should start creating a data management plan (DMP) early in your research process. A good DMP looks ahead at the full research lifecyle, from data collection to long-term preservation of research outputs. Below are some questions to think about and ideas to consider including in your plan.

::: {.panel-tabset}

## The data

**What are the data that will be collected or used, and where do they come from?** 

*Important management considerations:*

* Think about the content of the data, such as the variables (height, carbon content) or study subjects (humans, plants) being observed.
* Also think about the source of the data, such as whether they come from automatic sensors, human field observers, or previously-published datasets.
* Data content and source can dictate what data management options are available or required.

Detailed advice for collecting and managing different types of data begin in the [next chapter](collect-qa-describe.qmd).

## Storage & backup

**How will data be stored securely and protected from loss?** 

*Important management considerations:*

* Size of the data. Is it kilobyte or terabyte-scale?
* Data attributes like the data structure and file format can determine the available options for storage and backup.
* Institutional requirements, infrastructure capacity, and funding also constrain the options here.

## Metadata

**What kind of metadata will be used to describe the data?** 

*Important management considerations:*

* Plan to collect metadata during the research, not just in a final rush before publication.
* Some data types and corresponding file types, geospatial data for example, require specific metadata to be useful. 
* Research communities often have accepted standards for metadata content and formatting.

## Access & sharing

**How will data access be provided during research, and how will research data products be shared?** 

*Important management considerations:*

* The research team should have secure access to data as necessary.
* Data publication is generally required for federally-supported research, so plan for this early.
* Be aware of your team's, and your broader research community's, expectations for sharing data.

## Preservation

**What are the long-term plans for preservation of the data (or samples/specimens) once research is complete?** 

*Important management considerations:*

* Research funding may (again) dictate a particular location or duration for data preservation.
* If data re-use is likely, choose long-term preservation options accordingly.
* Complete metadata is essential to making datasets useful for the long-term. 

## Roles

**What are the data management roles and who is responsible for what?** 

*Important management considerations:*

* Some potentially important roles: data collection, quality assurance and control (QA/QC), cyberinfrastructure technician, analysis, data curation and publication.
* People in data roles frequently turn over, so plan on some role-sharing to help overcome the "Bus factor."
* Be prepared to give credit to people in these roles when publishing research products.

:::

### For proposals

 A formal data management plan (DMP) document is usually required in proposals to federal agencies and other funders. For example, in standard proposals, NSF expects a 2-page DMP with these suggested sections:

> 1. the types of data, samples, physical collections, software, curriculum materials, and other materials to be produced in the course of the project;
> 2. the standards to be used for data and metadata format and content (where existing standards are absent or deemed inadequate, this should be documented along with any proposed solutions or remedies);
> 3. policies for access and sharing including provisions for appropriate protection of privacy, confidentiality, security, intellectual property, or other rights or requirements;
> 4. policies and provisions for re-use, re-distribution, and the production of derivatives; and
> 5. plans for archiving data, samples, and other research products, and for preservation of access to them.
>
> *from [Chapter 2 of the 2024 NSF PAPPG](https://www.nsf.gov/policies/pappg/24-1/ch-2-proposal-preparation#ch2D2i-ii)*[^1]

Some grant programs have more or less extensive plan requirements. The Jornada Basin LTER program submits a fairly long DMP with each renewal proposal to the NSF LTER program (examples [here](../../proposals-and-reports/index.qmd)). We follow this plan closely during our 6-year funding cycle, and many of the recommendations and expectations outlined in this guide are targeted to help fulfill our proposal DMP.

**Here are some resources that can help with creating a proposal DMP:**

* [DMPtool.org](https://dmptool.org) collects DMP templates matching institutional and funder requirements, and provides examples from many existing research programs and data repositories. It is oriented towards a wide range of major U.S. funding agencies (NSF, NIH, etc.)
* Here are the [NSF guidelines](https://www.nsf.gov/funding/data-management-plan) for data management and sharing plans. [^2]
* Data management planning guides for federal agency scientists are generally available from the agency itself, such as for [USDA](https://www.nal.usda.gov/services/data-management-planning) and [USGS](https://www.usgs.gov/data-management/data-management-plans).
* **If you need help creating a DMP for a project proposal at the Jornada, the Jornada IM team has a fair amount of experience and can give advice.**

[^1]: The [NSF Proposal & Award Policies & Procedures Guide](https://www.nsf.gov/policies/pappg), or PAPPG, is the comprehensive proposal-writing guide for NSF submitters. All NSF proposals need to follow the requirements in the PAPPG except when a specific program solicitation requests something different or additional.
[^2]: This is a summary extracted from the most recent version of the PAPPG.


## Updating your plan and project information

Please update the Jornada Research Site Manager (<cwnelson@nmsu.edu>) with changes to projects using updated ResNotif forms at least once per year. Send updates about project personnel or website information to the IM team (<jornada.data@nmsu.edu>) as necessary.