---
title: Overview for Information Managers
---

This is the full documentation for the Jornada Basin LTER Information Management system, covering technical aspects of our data publishing process, data management tools, and administration of public-facing information like the website and data catalog. Researchers and data users should start at the [Jornada IM web pages](https://jornada-im.github.io/) to get started with Jornada data management.  **This is a DRAFT document.**

### Table of contents

Preface: [The JRN LTER Data Management Plan](JRN_LTER_data_management_plan.v3.md)

Chapters:

1. Research & data management overview
    - [Introduction](chap1-overview.md#introduction)
    - [Research project management](chap1-overview.md#research-project-management)
    - [Research data management](chap1-overview.md#research-data-management)
    - [Public dataset listings](chap1-overview.md#dataset-listings)
    - [Bibliographies](chap1-overview.md#bibliographies)
    - [Local servers](chap1-overview.md#local-computing-resources)
    - [Hosted services (external)](chap1-overview.md#hosted-resources)
    
2. Policy and procedures
    - Research notifications and approval
    - Data access policies
    - Metadata and data submission

3. General systems administration
    - [Server & cloud administration](server_admin.md)

4. Data collection and quality assurance
    - Archiving data on network shares
    - GCE and MATLAB extensions
    - Scripted QA/QC

5. Metadata collection and standards
    - [Metadata standards](jornada_metadata_standards.md)

6. JRN Metabase
    - [Installation and configuration](chap-jrn-metabase.md#setup)
    - [Server and database administration](chap-jrn-metabase.md#administration)
    - [The LTER Metabase schema and data model](chap-jrn-metabase.md#metabase-schema-and-data-model)
    - [Populating a new database](chap-jrn-metabase.md#populating-metabase)
    - [Create and update datasets](chap-jrn-metabase.md#create-and-update-datasets)
    - [PostgreSQL help links](chap-jrn-metabase.md#postgres-links)

7. Publishing Jornada datasets
    - [Overview, conventions, and standards](chap-publishing-data.md#introduction)
    - [Making EML with JRN Metabase](chap-publishing-data.md#make-eml-with-jrn-metabase-and-jerald)
        + SOP for entering metadata in Metabase: [docx](SOP_Metadata_Publishing.docx), [web page](sop_metadata_publishing) (draft)
    - [Making EML with EMLassemblyline](chap-publishing-data.md#make-eml-with-emlassemblyline)

8. Project management
	1. Project database
	2. Personnel updates
	3. Publication updates

9. The JRN website and other communication platforms
    - [The JRN Website](chap-website-and-comm.md#the-jrn-website) - an overview
    - [Website content](chap-website-and-comm.md#website-content)
    - [Website apps](chap-website-and-comm.md#website-apps)
      + [The data catalogs](chap-website-and-comm.md#data-catalogs)
      + [Zotero bibliography](chap-website-and-comm.md#zotero-bibliography)
      + [Interactive data viewer](chap-website-and-comm.md#interactive-data-viewer)
    - [Shared mailing lists](chap-website-and-comm.md#mailing-lists)


9. Tools and apps
    - Guide to Jornada-IM repositories
    - Analytics apps
    - DSIS

10. Hacks
    - [Parse trello boards to CSV format](parse_trello_boards.md)

11. External data, partnerships, and collaboration
    - Collaborations with USDA-ARS data managers
    - Asombro data
    - NEON data

12. Annual reports
    - [2020](reports/JRN_IM_annual_report_2020.md)
    - [2021](reports/JRN_IM_annual_report_2021.md)



Jornada data managers, including the IM team, should follow LTER and Jornada standards and best practices when creating metadata files and publishing research data packages. 

# Dataset tracking

We use Trello for this. For LTER datasets there are three Trello boards that represent how Jornada datasets are split into three categories:

1. Core - ongoing, high priority datasets that are updated regularly (once per year we hope). Many of these are collected by the JRN field crew.
2. Non-core - lower-priority and completed datasets.
3. Works in progress ('WIP') - datasets that are brand new or as-yet unpublished. Many are in the development/review phase, or are awaiting publication of results associated with the data.

Contact someone on the IM team to get added to these boards.

# Data management resources

If you are wondering whether the content or format of a metadata file (EML) is correct and complete, see our metadata standards documents. They are specific to Jornada Basin LTER data packages. **THESE ARE DRAFTS** and subject to change!

* [General Jornada metadata standards](https://jornada-im.github.io/documentation/JRN_metadata_standards) for all data packages (this is a bit out of date)
* [Jornada keyword thesauri](https://github.com/jornada-im/documentation/raw/main/standards_src/keyword_thesauri.xlsx) (.xlsx) list keywords that should appear in all Jornada metadata files.
* Also see the full [Jornada IM documentation pages](https://jornada-im.github.io/documentation)


## standards

A directory of documents about best practices and standards for metadata creation at Jornada Basin LTER.

Please refer to these as you are packaging data and creating EML documents for Jornada Basin research products.

**Edit as you see fit, but please track your changes when possible and Greg will try to sync with the GitHub version of this repository.**